package edu.emory.oit.vpcprovisioning.shared;

import java.util.Date;
import java.util.List;

import com.google.gwt.user.client.rpc.IsSerializable;
import com.google.gwt.view.client.ProvidesKey;

@SuppressWarnings("serial")
public class FirewallExceptionRequestPojo extends SharedObject implements IsSerializable, Comparable<FirewallExceptionRequestPojo> {
	String systemId;
	String userNetId;
	String applicationName;
	String isSourceOutsideEmory;
	String timeRule;
	Date validUntilDate;
	String sourceIp;
	String destinationIp;
	String ports;
	String businessReason;
	String isPatched;
	String isDefaultPasswdChanged;
	String isAppConsoleACLed;
	String isHardened;
	String patchingPlan;
	List<String> compliance = new java.util.ArrayList<String>();
	String otherCompliance;
	String sensitiveDataDesc;
	String localFirewallRules;
	String isDefaultDenyZone;
	List<String> tags = new java.util.ArrayList<String>();
	String requestNumber;
	String requestState;
	String requestItemNumber;
	String requestItemState;
	
	/*
	(SystemId?, UserNetID, ApplicationName, 
	IsSourceOutsideEmory, TimeRule, ValidUntilDate?, SourceIpAddresses, DestinationIpAddresses, 
	Ports, BusinessReason, IsPatched, IsDefaultPasswdChanged, IsAppConsoleACLed, IsHardened, 
	PatchingPlan, Compliance*, OtherCompliance?, SensitiveDataDesc, LocalFirewallRules, 
	IsDefaultDenyZone, Tag+, RequestNumber?, RequestState?, RequestItemNumber?,  RequestItemState?, 
	CreateDatetime?, UpdateDatetime?)>
	 
	SystemId?, ServiceNow internal id to uniquely identify a record in the custom table. Not required in create. Required for update/delete.  wsdl: sys_id
	UserNetID, Form: requestor userID; wsdl: u_requested_for
	ApplicationName,   Form: For what application is this firewall exception needed.  wsdl: u_common_name
	IsSourceOutsideEmory,  Form:Is the source outside of Emory's network and the destination inside?.  Valid values: Yes, No.  wsdl: u_internet_access
	TimeRule,  how long the firewall exception will be valid.  Valid values: Indefinitely, SpecificDate.  wsdl: u_how_long
	ValidUntilDate?,  if ValidUntil is SpecificDate, this field holds the date string, such as 2018-11-14. wsdl: u_specific_date 
	SourceIpAddresses,  Source IP addresses AND fully qualified domain names of the system(s) that need to access the destination(s).  wsdl: u_ip_address 
	DestinationIpAddresses, Destination IP address(es) AND fully qualified domain name(s) of the system(s) that needs to be accessible through the firewall.  wsdl: u_ip_address2 
	Ports,  Destination ports, applications, or services that need to be accessible. Indicate TCP or UDP for each, or ICMP type, along with the underlying protocol or application.  wsdl: u_ports 
	BusinessReason, - Describe the business justification for this exception.  wsdl: u_business_reason 
	IsPatched, - Are Server/Service/Application components fully patched at the time of this request?  valie values: Yes, No.  wsdl: u_patch_server 
	IsDefaultPasswdChanged, - Have all default application or server passwords been changed? valid values: Yes, No.  wsdl: u_app_pswd 
	IsAppConsoleACLed, - Have all administrative/management consoles for the application, as well as any underlying technology administrative/management consoles (such as ColdFusion, Jboss, Tomcat, phpmyadmin) been properly ACL'd. valid values: Yes, No. wsdl: u_mgmt_consol 
	IsHardened, - Have hardening guidelines for the application/service and underlying technologies been followed and implemented? Valid values: Yes, No.  wsdl:  u_guidelines 
	PatchingPlan, - Describe your plan for keeping this application/service and underlying technologies patched in a timely manner.  wsdl: u_plan 
	Compliance*, - Is this application/service in scope of any of the following compliance regimes? valid values: FERPA, FISMA, HIPAA, PCI, Other, Unsure. wsdl: u_comp_1 to u_comp_6 
	OtherCompliance?, - compliance description when the Compliance value is "Other".  wsdl: u_other_compliance 
	SensitiveDataDesc, - Describe any sensitive data that will be stored or processed on this system.  wsdl: u_sensitivity 
	LocalFirewallRules, - Describe any local (host-based) firewall rules that are currently configured on the system.  wsdl: u_firewall_rules 
	IsDefaultDenyZone, - Could this system be placed into a subnet that blocks all outbound Internet traffic by default.  valid values: Yes, No.  wsdl: u_subnet 
	Tag+, - tags for this request.  wsdl: u_tag
	RequestNumber?,  - ServiceNow request number, generated by the create call internally.  wsdl: u_req_number 
	RequestState?, - status of this request, updated by ServiceNow.  Valid values:Open, Pending, Work In Progress, Skip Task, Task Incomplete, Closed Complete.  wsdl: u_req_state 
	RequestItemNumber?,  - ServiceNow request item number, generated by the create call internally.  wsdl: u_ritm_number 
	RequestItemState?, - ServiceNow request item state, updated by ServiceNow request fulfillment.  This is the value that an application should check for Request state for custom requests. Valid values:Open, Pending, Work In Progress, Skip Task, Task Incomplete, Closed Complete.  wsdl: u_ritm_state.  This field has the actual fulfillment status for the firewall request 
	CreateDateTime?,  - the date and time when the request is created.  Populated by SN.
	UpdateDateTime? - the date and time when the request is updated, either by requestor or the fulfiller.  Populated by SN.
	
             <UserNetID>gwang28</UserNetID>
             <ApplicationName>JBossEAP</ApplicationName>
             <IsSourceOutsideEmory>No</IsSourceOutsideEmory>
             <TimeRule>SpecificDate</TimeRule>
             <ValidUntilDate>2020-12-31</ValidUntilDate>
             <SourceIpAddresses>10.231.51.207</SourceIpAddresses>
             <DestinationIpAddresses>23.20.53.144</DestinationIpAddresses>
             <Ports>443</Ports>
             <BusinessReason>access EC2 instances in AWS</BusinessReason>
             <IsPatched>Yes</IsPatched>
             <IsDefaultPasswdChanged>Yes</IsDefaultPasswdChanged>
             <IsAppConsoleACLed>Yes</IsAppConsoleACLed>
             <IsHardened>Yes</IsHardened>
             <PatchingPlan>quarterly patching by LITS</PatchingPlan>
             <Compliance>HIPAA</Compliance> 
             <Compliance>Other</Compliance>
             <OtherCompliance>SOX</OtherCompliance>
             <SensitiveDataDesc>financial information</SensitiveDataDesc>
             <LocalFirewallRules></LocalFirewallRules>
             <IsDefaultDenyZone>Yes</IsDefaultDenyZone>
             <Tag>vpc-2f09a348</Tag>
             <Tag>SOM</Tag>
             <Tag>Emory</Tag>
	 */

	public static final ProvidesKey<FirewallExceptionRequestPojo> KEY_PROVIDER = new ProvidesKey<FirewallExceptionRequestPojo>() {
		@Override
		public Object getKey(FirewallExceptionRequestPojo item) {
			return item == null ? null : item.getSystemId();
		}
	};

	public FirewallExceptionRequestPojo() {
		// TODO Auto-generated constructor stub
	}

	@Override
	public int compareTo(FirewallExceptionRequestPojo o) {
		// TODO Auto-generated method stub
		return 0;
	}

	public String getSystemId() {
		return systemId;
	}

	public void setSystemId(String systemId) {
		this.systemId = systemId;
	}

	public String getUserNetId() {
		return userNetId;
	}

	public void setUserNetId(String userNetId) {
		this.userNetId = userNetId;
	}

	public String getApplicationName() {
		return applicationName;
	}

	public void setApplicationName(String applicationName) {
		this.applicationName = applicationName;
	}

	public String getIsSourceOutsideEmory() {
		return isSourceOutsideEmory;
	}

	public void setIsSourceOutsideEmory(String isSourceOutsideEmory) {
		this.isSourceOutsideEmory = isSourceOutsideEmory;
	}

	public String getTimeRule() {
		return timeRule;
	}

	public void setTimeRule(String timeRule) {
		this.timeRule = timeRule;
	}

	public Date getValidUntilDate() {
		return validUntilDate;
	}

	public void setValidUntilDate(Date validUntilDate) {
		this.validUntilDate = validUntilDate;
	}

	public String getSourceIp() {
		return sourceIp;
	}

	public void setSourceIp(String sourceIp) {
		this.sourceIp = sourceIp;
	}

	public String getDestinationIp() {
		return destinationIp;
	}

	public void setDestinationIp(String destinationIp) {
		this.destinationIp = destinationIp;
	}

	public String getPorts() {
		return ports;
	}

	public void setPorts(String ports) {
		this.ports = ports;
	}

	public String getBusinessReason() {
		return businessReason;
	}

	public void setBusinessReason(String businessReason) {
		this.businessReason = businessReason;
	}

	public String getIsPatched() {
		return isPatched;
	}

	public void setIsPatched(String isPatched) {
		this.isPatched = isPatched;
	}

	public String getIsDefaultPasswdChanged() {
		return isDefaultPasswdChanged;
	}

	public void setIsDefaultPasswdChanged(String isDefaultPasswdChanged) {
		this.isDefaultPasswdChanged = isDefaultPasswdChanged;
	}

	public String getIsAppConsoleACLed() {
		return isAppConsoleACLed;
	}

	public void setIsAppConsoleACLed(String isAppConsoleACLed) {
		this.isAppConsoleACLed = isAppConsoleACLed;
	}

	public String getIsHardened() {
		return isHardened;
	}

	public void setIsHardened(String isHardened) {
		this.isHardened = isHardened;
	}

	public String getPatchingPlan() {
		return patchingPlan;
	}

	public void setPatchingPlan(String patchingPlan) {
		this.patchingPlan = patchingPlan;
	}

	public List<String> getCompliance() {
		return compliance;
	}

	public void setCompliance(List<String> compliance) {
		this.compliance = compliance;
	}

	public String getOtherCompliance() {
		return otherCompliance;
	}

	public void setOtherCompliance(String otherCompliance) {
		this.otherCompliance = otherCompliance;
	}

	public String getSensitiveDataDesc() {
		return sensitiveDataDesc;
	}

	public void setSensitiveDataDesc(String sensitiveDataDesc) {
		this.sensitiveDataDesc = sensitiveDataDesc;
	}

	public String getLocalFirewallRules() {
		return localFirewallRules;
	}

	public void setLocalFirewallRules(String localFirewallRules) {
		this.localFirewallRules = localFirewallRules;
	}

	public String getIsDefaultDenyZone() {
		return isDefaultDenyZone;
	}

	public void setIsDefaultDenyZone(String isDefaultDenyZone) {
		this.isDefaultDenyZone = isDefaultDenyZone;
	}

	public List<String> getTags() {
		return tags;
	}

	public void setTags(List<String> tags) {
		this.tags = tags;
	}

	public String getRequestNumber() {
		return requestNumber;
	}

	public void setRequestNumber(String requestNumber) {
		this.requestNumber = requestNumber;
	}

	public String getRequestState() {
		return requestState;
	}

	public void setRequestState(String requestState) {
		this.requestState = requestState;
	}

	public String getRequestItemNumber() {
		return requestItemNumber;
	}

	public void setRequestItemNumber(String requestItemNumber) {
		this.requestItemNumber = requestItemNumber;
	}

	public String getRequestItemState() {
		return requestItemState;
	}

	public void setRequestItemState(String requestItemState) {
		this.requestItemState = requestItemState;
	}

}
